# Syntax Prime V2 - Railway Deployment Configuration
# Fixed startup command for Railway environment variables

[build]
builder = "dockerfile"

[deploy]
startCommand = "python -m uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1 --log-level info"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3